version: '2'
services:
  app:
    build: .
    image: "app:${TAG}"
    command: bundle exec puma -C config/puma.rb
    volumes:
      - /var/www/sample_rails_docker_app
    expose:
      - "3000"
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: "web:${TAG}"
    links:
      - app
    ports:
      - "80:80"
