version: '2'
services:
  app:
    build: .
    dockerfile: production.Dockerfile
    image: "app:${TAG}"
    command: bundle exec puma -C config/puma.rb
    volumes:
      - /var/www/sample_rails_docker_app
    expose:
      - "3000"
  web:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: "web:${TAG}"
    links:
      - app
    ports:
      - "80:80"
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
