version: '2'
services:
  app:
    build:
      context: .
      dockerfile: production.Dockerfile
    image: "app:${TAG}"
    command: bundle exec puma -C config/puma.rb
    volumes:
      - assets:/apps/railsgoat/current
    expose:
      - "3000"
  web:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: "web:${TAG}"
    volumes:
      - assets:/apps/railsgoat/current
    links:
      - app
    ports:
      - "80:80"

volumes:
  assets:
