development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  username: <%= ENV['railsgoat_db_username'] %>
  password: <%= ENV['railsgoat_db_password'] %>
  host: <%= ENV['railsgoat_db_address'] %>
  port:  5432
